
//////////////////// STRINGS

const Strings = {

    "ST1": "RealFood",
    "ST2": "Home",
    "ST3": "Search",
    "ST4": "Favorites",
    "ST5": "Members",
    "ST6": "Profile",
    "ST7": "Contact Us",
    "ST8": "Terms and Conditions",
    "ST9": "Sign Out",
    "ST10": "Sign In",
    "ST11": "Sign Up",
    "ST12": "Don't have an account?",
    "ST13": "Already have an account?",
    "ST14": "I Agree to Terms and Conditions",
    "ST15": "Forgot Password?",
    "ST16": "Need Help? Contact Us",
    "ST17": "Enter",
    "ST18": "Name",
    "ST19": "Email",
    "ST20": "Password",
    "ST21": "Real Food. Real Simple",
    "ST22": "Browse Recipes",
    "ST23": "Featured Recipes",
    "ST24": "Featured Categories",
    "ST25": "Latest Recipes",
    "ST26": "Serv.",
    "ST27": "Prep Time",
    "ST28": "Categories",
    "ST29": "MyFeed",
    "ST30": "No Content Found",
    "ST31": "Please Wait...",
    "ST32": "Something Wrong",
    "ST33": "Please Complete The Form",
    "ST34": "Sign In",
    "ST35": "Sign Up",
    "ST36": "Email Already Exists",
    "ST37": "Email Doesn't Exist",
    "ST38": "Password Updated",
    "ST39": "Password Reset Email Sent",
    "ST40": "Ok",
    "ST41": "Need Help?",
    "ST42": "Contact Us",
    "ST43": "Reset Password",
    "ST44": "Any",
    "ST45": "Dificult",
    "ST46": "Servings",
    "ST47": "Ingredients",
    "ST48": "No Results Found",
    "ST49": "Instructions",
    "ST50": "By",
    "ST51": "Nutrition Facts",
    "ST52": "Calories",
    "ST53": "Total Fat",
    "ST54": "Protein",
    "ST55": "Carbs",
    "ST56": "Find a recipe...",
    "ST57": "Likes",
    "ST58": "Following",
    "ST59": "Followers",
    "ST60": "My Recipes",
    "ST65": "Ooops! No Results",
    "ST66": "Try different keywords or remove search filters",
    "ST67": "Results",
    "ST68": "Total",
    "ST69": "Follow",
    "ST70": "Unfollow",
    "ST71": "You can't follow your account",
    "ST72": "No content in this feed",
    "ST74": "Try Again",
    "ST76": "Done",
    "ST77": "Cancel",
    "ST78": "Save",
    "ST85": "Description",
    "ST88": "Comments",
    "ST89": "Show Comments",
    "ST90": "No Comments Found",
    "ST91": "Submit Comment",
    "ST92": "Share",
    "ST96": "Submit",
    "ST97": "Thank You",
    "ST98": "Your message has been submitted",
    "ST99": "Your message could not be sent",
    "ST100": "Get In Touch",
    "ST101": "Use the form below to drop us an e-mail",
    "ST102": "View other replies",
    "ST103": "Your Comment",
    "ST104": "Error",
    "ST105": "You have requested too many password resets.",
    "ST106": "Remove",
    "ST108": "My Recipes",
    "ST110": "About Us",
    "ST111": "Load More...",
    "ST112": "No More Items",
    "ST113": "Submit Recipe",

};

export default Strings;
